<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
var menus = [

	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"管理员管理",
                        "menuJump":"列表",
                        "tableName":"users"
                    }
                ],
                "menu":"管理员信息"
            }

            ,{
                "child":[
                    {
                        "buttons":[
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"轮播图管理",
                        "menuJump":"列表",
                        "tableName":"config"
                    }
                ],
                "menu":"轮播图信息"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"帖子类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryForum"
                    }
                    ,
                    {
                        "buttons":[
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"公告类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryGonggao"
                    }
                    ,
                    {
                        "buttons":[
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"畜禽养殖类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryChuqinyangzhi"
                    }
                    ,
                    {
                        "buttons":[
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"瓜果蔬菜类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryGuaguoshucai"
                    }
                    ,
                    {
                        "buttons":[
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"农业科技类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryNongyekeji"
                    }
                    ,
                    {
                        "buttons":[
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"水产养殖类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryShuichanyangzhi"
                    }
                    ,
                    {
                        "buttons":[
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"土壤肥料类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryTurangfeiliao"
                    }
                ],
                "menu":"基础数据管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"论坛管理",
                        "menuJump":"列表",
                        "tableName":"forum"
                    }
                ],
                "menu":"论坛管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"公告管理",
                        "menuJump":"列表",
                        "tableName":"gonggao"
                    }
                ],
                "menu":"公告管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"留言板管理",
                        "menuJump":"列表",
                        "tableName":"liuyan"
                    }
                ],
                "menu":"留言板管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"畜禽养殖管理",
                        "menuJump":"列表",
                        "tableName":"chuqinyangzhi"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"畜禽养殖留言管理",
                        "menuJump":"列表",
                        "tableName":"chuqinyangzhiLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"畜禽养殖收藏管理",
                        "menuJump":"列表",
                        "tableName":"chuqinyangzhiCollection"
                    }
                ],
                "menu":"畜禽养殖管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"瓜果蔬菜管理",
                        "menuJump":"列表",
                        "tableName":"guaguoshucai"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"瓜果蔬菜留言管理",
                        "menuJump":"列表",
                        "tableName":"guaguoshucaiLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"瓜果蔬菜收藏管理",
                        "menuJump":"列表",
                        "tableName":"guaguoshucaiCollection"
                    }
                ],
                "menu":"瓜果蔬菜管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"农业科技管理",
                        "menuJump":"列表",
                        "tableName":"nongyekeji"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"农业科技留言管理",
                        "menuJump":"列表",
                        "tableName":"nongyekejiLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"农业科技收藏管理",
                        "menuJump":"列表",
                        "tableName":"nongyekejiCollection"
                    }
                ],
                "menu":"农业科技管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"水产养殖管理",
                        "menuJump":"列表",
                        "tableName":"shuichanyangzhi"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"水产养殖留言管理",
                        "menuJump":"列表",
                        "tableName":"shuichanyangzhiLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"水产养殖收藏管理",
                        "menuJump":"列表",
                        "tableName":"shuichanyangzhiCollection"
                    }
                ],
                "menu":"水产养殖管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"土壤肥料管理",
                        "menuJump":"列表",
                        "tableName":"turangfeiliao"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"土壤肥料留言管理",
                        "menuJump":"列表",
                        "tableName":"turangfeiliaoLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"土壤肥料收藏管理",
                        "menuJump":"列表",
                        "tableName":"turangfeiliaoCollection"
                    }
                ],
                "menu":"土壤肥料管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"用户管理",
                        "menuJump":"列表",
                        "tableName":"yonghu"
                    }
                ],
                "menu":"用户管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"管理员",
        "tableName":"users"
    }
];

var hasMessage = '';
